#ifndef ATLANTRONIC_MODEL_H
#define ATLANTRONIC_MODEL_H

enum
{
	MODEL_IRQ_OUT_ENCODER_RIGHT,
	MODEL_IRQ_OUT_ENCODER_LEFT,
	MODEL_IRQ_OUT_I_RIGHT,
	MODEL_IRQ_OUT_I_LEFT,
	MODEL_IRQ_OUT_I_MOT3,
	MODEL_IRQ_OUT_I_MOT4,
	MODEL_IRQ_OUT_X,
	MODEL_IRQ_OUT_Y,
	MODEL_IRQ_OUT_ALPHA,
	MODEL_IRQ_OUT_NUM
};

#endif
