#ifndef ATLANTRONIC_MODEL_H
#define ATLANTRONIC_MODEL_H

enum
{
/*	MODEL_IRQ_OUT_ENCODER1,
	MODEL_IRQ_OUT_ENCODER2,
	MODEL_IRQ_OUT_ENCODER3,
	MODEL_IRQ_OUT_ENCODER4,
	MODEL_IRQ_OUT_ENCODER5,
	MODEL_IRQ_OUT_ENCODER6,
	MODEL_IRQ_OUT_I1,
	MODEL_IRQ_OUT_I2,
	MODEL_IRQ_OUT_I3,
	MODEL_IRQ_OUT_I4,
	MODEL_IRQ_OUT_I5,
	MODEL_IRQ_OUT_I6,
	MODEL_IRQ_OUT_X,
	MODEL_IRQ_OUT_Y,
	MODEL_IRQ_OUT_THETA,*/
	MODEL_IRQ_OUT_USART_AX12,
	MODEL_IRQ_OUT_NUM
};

enum
{
	MODEL_IRQ_IN_USART_AX12,
	MODEL_IRQ_IN_NUM,
};

#endif
