#ifndef ATLANTRONIC_GPIO_H
#define ATLANTRONIC_GPIO_H

enum
{
	GPIO_IRQ_OUT_PIN0 = 0,
	GPIO_IRQ_OUT_PIN1,
	GPIO_IRQ_OUT_PIN2,
	GPIO_IRQ_OUT_PIN3,
	GPIO_IRQ_OUT_PIN4,
	GPIO_IRQ_OUT_PIN5,
	GPIO_IRQ_OUT_PIN6,
	GPIO_IRQ_OUT_PIN7,
	GPIO_IRQ_OUT_PIN8,
	GPIO_IRQ_OUT_PIN9,
	GPIO_IRQ_OUT_PIN10,
	GPIO_IRQ_OUT_PIN11,
	GPIO_IRQ_OUT_PIN12,
	GPIO_IRQ_OUT_PIN13,
	GPIO_IRQ_OUT_PIN14,
	GPIO_IRQ_OUT_PIN15,
	GPIO_IRQ_OUT_CHANGE_PIN,
	GPIO_IRQ_OUT_NUM
};

#define PIN_NUM        16

#endif
