#ifndef ATLANTRONIC_MODEL_H
#define ATLANTRONIC_MODEL_H

enum
{
	MODEL_IRQ_OUT_CAN1_MSG_ID,
	MODEL_IRQ_OUT_CAN1_MSG_SIZE,
	MODEL_IRQ_OUT_CAN1_MSG_DATA_L,
	MODEL_IRQ_OUT_CAN1_MSG_DATA_H,
	MODEL_IRQ_OUT_USART_HOKUYO1,
	MODEL_IRQ_OUT_USART_HOKUYO2,
	MODEL_IRQ_OUT_USART_AX12,
	MODEL_IRQ_OUT_USART_RX24,
	MODEL_IRQ_OUT_ENCODER1,
	MODEL_IRQ_OUT_ENCODER2,
	MODEL_IRQ_OUT_ENCODER3,
	MODEL_IRQ_OUT_GPIO_0,
	MODEL_IRQ_OUT_GPIO_1,
	MODEL_IRQ_OUT_GPIO_2,
	MODEL_IRQ_OUT_GPIO_3,
	MODEL_IRQ_OUT_GPIO_4,
	MODEL_IRQ_OUT_GPIO_5,
	MODEL_IRQ_OUT_GPIO_6,
	MODEL_IRQ_OUT_GPIO_7,
	MODEL_IRQ_OUT_GPIO_8,
	MODEL_IRQ_OUT_GPIO_9,
	MODEL_IRQ_OUT_GPIO_10,
	MODEL_IRQ_OUT_GPIO_11,
	MODEL_IRQ_OUT_GPIO_GO,
	MODEL_IRQ_OUT_NUM
};

enum
{
	MODEL_IRQ_IN_CAN1_MSG_ID,
	MODEL_IRQ_IN_CAN1_MSG_SIZE,
	MODEL_IRQ_IN_CAN1_MSG_DATA_L,
	MODEL_IRQ_IN_CAN1_MSG_DATA_H,
	MODEL_IRQ_IN_ENCODER1,
	MODEL_IRQ_IN_ENCODER2,
	MODEL_IRQ_IN_ENCODER3,
	MODEL_IRQ_IN_PWM1,
	MODEL_IRQ_IN_PWM2,
	MODEL_IRQ_IN_PWM3,
	MODEL_IRQ_IN_PWM4,
	MODEL_IRQ_IN_PWM_DIR1,
	MODEL_IRQ_IN_PWM_DIR2,
	MODEL_IRQ_IN_PWM_DIR3,
	MODEL_IRQ_IN_PWM_DIR4,
	MODEL_IRQ_IN_USART_HOKUYO1,
	MODEL_IRQ_IN_USART_HOKUYO2,
	MODEL_IRQ_IN_USART_AX12,
	MODEL_IRQ_IN_USART_RX24,
	MODEL_IRQ_IN_LCD,
	MODEL_IRQ_IN_NUM,
};

enum
{
	EVENT_NEW_OBJECT = 1,
	EVENT_MOVE_OBJECT,
	EVENT_MANAGE_CAN_MOTOR,
	EVENT_SET_IO,
	EVENT_SET_POSITION,
	EVENT_SET_MAX_CYCLE_COUNT,
	EVENT_SET_ROBOT_PARAMETERS,
};

enum
{
	EVENT_MANAGE_CAN_MOTOR_CONNECT,
	EVENT_MANAGE_CAN_MOTOR_DISCONNECT,
};

typedef struct
{
	uint32_t type;        //!< type
	union
	{
		uint8_t data[256];     //!< données
		uint32_t data32[64];   //!< données
	};
} QemuAtlantronicModelEvent;

typedef struct
{
	float odoWheel1Radius;
	float odoWheel2Radius;
	char odoWheel1Way;
	char odoWheel2Way;
	uint16_t odoEncoderResolution;
	float voieOdo;
	float voieMot;
	float driving1WheelRaduis;
	float driving2WheelRaduis;
	uint32_t motorEncoderResolution;
	float drivingMotor1Red;
	float drivingMotor2Red;
	uint16_t canDrivingMotors;
	float halfLength;
	float halfWidth;
} __attribute__((packed)) QemuRobotParameters;

#endif
