#ifndef ATLANTRONIC_DYNAMIXEL_H
#define ATLANTRONIC_DYNAMIXEL_H

enum
{
	DYNAMIXEL_IRQ_IN_ID,
	DYNAMIXEL_IRQ_IN_USART_DATA,
	DYNAMIXEL_IRQ_IN_DISCONNECT,
	DYNAMIXEL_IRQ_IN_NUM
};

enum
{
	DYNAMIXEL_IRQ_OUT_USART_DATA,
	DYNAMIXEL_IRQ_OUT_USART_TX,
	DYNAMIXEL_IRQ_OUT_NUM
};

#endif
